In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import traceback
import sys
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('medical_insurance.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [7]:
df.sex.unique()

array(['female', 'male'], dtype=object)

In [9]:
df.sex.value_counts().to_dict()

{'male': 676, 'female': 662}

In [10]:
df.smoker.value_counts().to_dict()

{'no': 1064, 'yes': 274}

In [11]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [13]:
df.sex.replace({"male":1,"female":0},inplace=True)
df.smoker.replace({"no":0,"yes":1},inplace=True)

In [14]:
df = pd.get_dummies(df,columns=["region"])
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

# Hold out validation

In [15]:
x = df.drop('charges',axis=1)
y = df.charges

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=34)

In [17]:
x_train

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
414    19    0  35.150         0       0                 0                 1   
1279   25    0  26.790         2       0                 0                 1   
647    40    0  23.370         3       0                 1                 0   
764    45    0  25.175         2       0                 1                 0   
1133   52    0  18.335         0       0                 0                 1   
...   ...  ...     ...       ...     ...               ...               ...   
453    20    1  29.735         0       0                 0                 1   
324    29    1  27.200         0       0                 0                 0   
1109   45    1  20.350         3       0                 0                 0   
490    19    0  32.900         0       0                 0                 0   
1146   60    1  32.800         0       1                 0                 0   

      region_southeast  region_southwest  
414                  0                 0  
1279                 0                 0  
647                  0                 0  
764                  0                 0  
1133                 0                 0  
...                ...               ...  
453                  0                 0  
324                  0                 1  
1109                 1                 0  
490                  0                 1  
1146                 0                 1  

[1070 rows x 9 columns]

# Model creation

In [19]:
model = LinearRegression()

In [20]:
model.fit(x_train,y_train)

LinearRegression()

In [21]:
y_pred = model.predict(x_test)
y_pred

array([ 6.28742129e+03,  8.73545987e+03,  6.74917086e+03,  4.04040565e+03,
        7.41547104e+03,  8.68135666e+03,  5.63819787e+03,  9.52584095e+03,
        3.60274864e+04,  8.74202976e+03,  5.48794145e+03,  2.11594702e+03,
        9.64485286e+03,  7.37749415e+03,  3.87671160e+04,  1.31771917e+04,
        3.75134701e+04,  3.51944718e+03,  2.82012755e+03,  2.86152516e+04,
        3.00886611e+04,  1.43661944e+04,  1.09760259e+04,  2.55863651e+03,
        3.21856559e+04,  9.66485541e+03,  3.22826582e+03,  7.11505066e+03,
        5.55007242e+03,  9.37585237e+03,  2.83249950e+03,  3.64074859e+03,
        3.56046029e+04,  2.13830883e+03,  3.68994699e+04,  3.24564780e+04,
        6.19461909e+03,  3.44257047e+04,  3.25618588e+04,  1.18730500e+04,
        3.03715391e+04,  1.25023067e+04,  1.25293851e+03,  1.08528783e+04,
        4.00504591e+04,  6.87547027e+03,  8.58827184e+03,  4.39077775e+03,
        8.07318952e+03,  2.77303501e+03,  1.13518956e+04,  1.45384360e+04,
        1.44601192e+04,  

In [22]:
mse = mean_squared_error(y_test,y_pred)

In [23]:
mse

41587655.82548301

In [24]:
r2_value = r2_score(y_test,y_pred)
r2_value

0.7442111491697808

In [25]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [26]:
df.columns 


Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'],
      dtype='object')

In [28]:
age = 19
sex = 'male'
bmi = 27.9
children = 2
smoker = 'yes'
region = 'northeast'

# charges = ?

In [31]:
project_data = {'sex':{'female':0,'male':1},
                'smoker':{'no':0,'yes':1}}

region = "region_"+region

index = np.where(x.columns==region)

In [32]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
test_array[0] = age
test_array[1] = project_data['sex'][sex]
test_array[2] = bmi
test_array[3] = children
test_array[4] = project_data['smoker'][smoker]
test_array[index] = 1

In [34]:
test_array

array([19. ,  1. , 27.9,  2. ,  1. ,  1. ,  0. ,  0. ,  0. ])

In [36]:
y_prediction = model.predict([test_array])

In [40]:
f"predicted charges are : {round(y_prediction[0],2)}"

'predicted charges are : 27073.45'

In [41]:
import pickle
import json

In [42]:
with open('Linear_Model.pkl','wb') as f:
    pickle.dump(model,f)

In [44]:
pd.DataFrame(project_data).to_json('random.json')

In [45]:
with open('project_data.json','w') as f:
    json.dump(project_data,f)

In [48]:
list1 = [2,3,4]
with open('List1.pkl','wb') as f:
    pickle.dump(list1,f)

In [1]:

columns =['age', 'sex', 'bmi', 'children', 'smoker', 'charges',
'region_northeast', 'region_northwest', 'region_southeast',
'region_southwest']

In [3]:
region = 'southeast'
region = 'region_' +region
region

'region_southeast'

In [8]:
columns.index(region)

8

In [1]:
import os
os.getcwd()

'c:\\Users\\Pratik\\End_to_End_Project\\Satyajit\\Project2\\Project_app'

In [2]:
os.path.join('Project_app','Linear_Model.pkl')

'Project_app\\Linear_Model.pkl'